devbox-docker:
  image: manishgoyaler/devbox:latest
  volumes:
  - ~/devbox/workspace:/home/devbox/workspace
  - ~/.m2:/home/devbox/.m2
  ports:
  - "8080:8080"
  - "3000:3000"
  - "3001:3001"
  - "9000:9000"
  - "8888:8888"
  #- "5080:80"
  working_dir: /home/devbox/worspace
