devbox-nginx:
  image: nginx:latest
  volumes:
    - ~/devbox/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ~/devbox/nginx/html:/usr/share/nginx/html
  ports:
    - "80:80"
    - "443:443"
devbox-cassandra:
  image: cassandra:latest
  volumes:
    - ~/devbox/cassandra:/var/lib/cassandra
devbox-docker:
  build: devbox/
  volumes:
  - ~/devbox/workspace:/home/devbox/workspace
  - ~/.m2:/home/devbox/.m2
  ports:
  - "8080:8080"
  - "3000:3000"
  - "3001:3001"
  - "9000:9000"
  - "80:80"
  - "443:443"
  working_dir: /home/devbox/worspace
  links:
    - devbox-cassandra
