cassandra:
  image: cassandra:latest
  volumes:
    - ~/devbox/cassandra:/var/lib/cassandra
devbox-docker:
  container_name: devbox
  image: jdubois/devbox-docker
  volumes:
  - ~/devbox:/home/devbox/workspace
  - ~/.m2:/home/devbox/.m2
  ports:
  - "8080:8080"
  - "3000:3000"
  - "3001:3001"
  - "9000:9000"
  - "80:80"
  - "443:443"
  working_dir: /home/devbox/worspace
  links:
    - cassandra
