devbox-docker:
  image: manishgoyaler/devbox:latest
  #build: devbox/
  volumes:
  - ~/devbox/workspace:/home/devbox/workspace
  - ~/.m2:/home/devbox/.m2
  - ~/devbox/cassandra:/home/devbox/cassandra
  - ~/devbox/nginx:/home/devbox/nginx
  - ~/.ivy2:/home/devbox/.ivy2
  - ~/.sbt:/home/devbox/.sbt    
  ports:
  - "8080:8080"
  - "8443:8443"
  - "3000:3000"
  - "3001:3001"
  - "9000:9000"
  - "8888:8888"
  - "5080:80"
  - "7000:7000"
  - "7001:7001"
  - "9042:9042"
  - "54338:54338"
  working_dir: /home/devbox/workspace
  #links:
    #- devbox-cassandra
